"""empty message

Revision ID: 09ce168a116c
Revises: 2dad0ed2abac
Create Date: 2023-03-26 15:14:41.113830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ce168a116c'
down_revision = '2dad0ed2abac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likess',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('like_state', sa.Boolean(), nullable=True),
    sa.Column('liked_id', sa.Integer(), nullable=False),
    sa.Column('liker_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['liked_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['subscriber.id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likess')
    # ### end Alembic commands ###
