"""empty message

Revision ID: 2198b597a03f
Revises: 2eb80f69f289
Create Date: 2023-03-29 10:47:28.909352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2198b597a03f'
down_revision = '2eb80f69f289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.String(), nullable=False),
    sa.Column('Viewed_page', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed_pages')
    # ### end Alembic commands ###
