"""empty message

Revision ID: 2dad0ed2abac
Revises: 48c667e96967
Create Date: 2023-03-23 15:40:17.041279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dad0ed2abac'
down_revision = '48c667e96967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'content', ['content_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('content_id')

    # ### end Alembic commands ###
