"""empty message

Revision ID: 2eb80f69f289
Revises: da0cc81e4e1f
Create Date: 2023-03-28 14:01:14.166648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb80f69f289'
down_revision = 'da0cc81e4e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likess', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likereg', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_likess_likereg'), ['likereg'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likess', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likess_likereg'))
        batch_op.drop_column('likereg')

    # ### end Alembic commands ###
