"""empty message

Revision ID: 3b632549cdf9
Revises: 5442d1f439c5
Create Date: 2023-03-27 12:24:06.494575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b632549cdf9'
down_revision = '5442d1f439c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likess', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aliker_id', sa.String(), nullable=True))
        batch_op.alter_column('liker_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'creators', ['aliker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likess', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('liker_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('aliker_id')

    # ### end Alembic commands ###
