"""creators table

Revision ID: 7565e7c20943
Revises: cb694127f97a
Create Date: 2023-03-20 11:09:46.989422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7565e7c20943'
down_revision = 'cb694127f97a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_yourself', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verified_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('verified_date')
        batch_op.drop_column('verified')
        batch_op.drop_column('about_yourself')

    # ### end Alembic commands ###
