"""empty message

Revision ID: a6799c61e7d2
Revises: a73457d6f7f3
Create Date: 2023-03-31 08:00:32.857745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6799c61e7d2'
down_revision = 'a73457d6f7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewed_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewreg', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewed_pages', schema=None) as batch_op:
        batch_op.drop_column('viewreg')

    # ### end Alembic commands ###
