"""empty message

Revision ID: aa4de9c20be4
Revises: e92c5dd40954
Create Date: 2023-03-16 20:05:12.537431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa4de9c20be4'
down_revision = 'e92c5dd40954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.alter_column('creatorreg',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('confirmed_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_index('ix_creators_confirmed_on')
        batch_op.create_index(batch_op.f('ix_creators_creatorreg'), ['creatorreg'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creators_creatorreg'))
        batch_op.create_index('ix_creators_confirmed_on', ['confirmed_on'], unique=False)
        batch_op.alter_column('confirmed_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('creatorreg',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
