"""creators table

Revision ID: cb694127f97a
Revises: bed88290ec4e
Create Date: 2023-03-20 11:07:00.528112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb694127f97a'
down_revision = 'bed88290ec4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_yourself', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verified_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('verified_date')
        batch_op.drop_column('verified')
        batch_op.drop_column('about_yourself')

    # ### end Alembic commands ###
