"""empty message

Revision ID: da0cc81e4e1f
Revises: 3b632549cdf9
Create Date: 2023-03-28 10:17:32.391800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0cc81e4e1f'
down_revision = '3b632549cdf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_co', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('creator_co')

    # ### end Alembic commands ###
