"""empty message

Revision ID: e8d70b29da49
Revises: 2198b597a03f
Create Date: 2023-03-31 07:56:38.382351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d70b29da49'
down_revision = '2198b597a03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewed_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewreg', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewed_pages', schema=None) as batch_op:
        batch_op.drop_column('viewreg')

    # ### end Alembic commands ###
